backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/images"
public_folder: "src/game_details"

collections:

  - name: "games"
    label: "Games"
    folder: "src/game_details"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["game"] }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Bonus", name: "bonus", widget: "string" }
      - { label: "Minimum Withdraw", name: "withdraw", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Rank", name: "rank", widget: "number", min: 1 }

